M48
; DRILL file {KiCad 7.0.7} date 2024 January 02, Tuesday 00:36:13
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-02T00:36:13-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0591
%
G90
G05
T1
X5.2858Y-3.4
X5.3307Y-3.5
X5.4843Y-3.4
X5.5896Y-3.6
X5.6559Y-3.3563
X5.6591Y-3.5539
X5.6673Y-3.6
T2
X5.2Y-3.4
X5.2Y-3.5
X5.2Y-3.6
T3
X5.4Y-3.75
X5.5Y-3.25
X5.6Y-3.75
T0
M30
