name: Craft18
version: 0.1.0
author: gary600
main: xyz.gary600.craft18_plugin.Craft18Plugin
api-version: 1.20

permissions:
  craft18.configure:
    description: Allow configuration
    default: true

commands:
  port:
    description: View/configure Craft18 redstone ports
    usage: /port [0-4] [clear]
  serial:
    description: View/configure Craft18 serial port
    usage: /serial [<port>]|close|list
