M48
; DRILL file {KiCad 7.0.7} date 2024 January 02, Tuesday 00:34:10
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-02T00:34:10-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X5.9Y-4.1
X5.9Y-4.2
X5.9Y-4.3
X6.0Y-4.1
X6.0Y-4.2
X6.0Y-4.3
X6.1Y-4.1
X6.1Y-4.2
X6.1Y-4.3
T2
X5.55Y-4.2
X5.7Y-3.9
X5.7Y-4.5
X6.0Y-3.75
X6.0Y-4.65
X6.3Y-3.9
X6.3Y-4.5
X6.45Y-4.2
T0
M30
